name: Trigger Pull Request
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"You have a new pull request: "}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Action:* Pull Request"},{"type":"mrkdwn","text":"*Project:* dh-react-design-system"},{"type":"mrkdwn","text":"*Branch:* master"},{"type":"mrkdwn","text":"*Repo:* <https://github.com/lumisight-dev/dh-react-design-system/pulls>"},{"type":"mrkdwn","text":"*Created by:* ${{ github.event.pull_request.user.login }}"}]}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
