name: Trigger workflow run
on:
  workflow_run:
    workflows:
      - Deployment
    types:
      - completed
    branches:
      - master

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"You have a new request action: "}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Action:* Deploy to PROD"},{"type":"mrkdwn","text":"*Status:* SUCCEEDED!"},{"type":"mrkdwn","text":"*Project:* dh-react-design-system"}, {"type":"mrkdwn","text":"*Domain:* https://datahouse-react-design-system.web.app"}]}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"You have a new request action: "}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Action:* Deploy to PROD"},{"type":"mrkdwn","text":"*Status:* FAILED!"},{"type":"mrkdwn","text":"*Project:* dh-react-design-system"}, {"type":"mrkdwn","text":"*Domain:* https://datahouse-react-design-system.web.app"}, {"type":"mrkdwn","text": "<@U028F5J3FQT>"}]}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
